version: '2'
services:
  web:
    image: queerai:latest
    environment:
      - PYTHONUNBUFFERED=0
      - BASICAUTH_USERNAME
      - BASICAUTH_PASSWORD
    depends_on:
      - redis
    ports:
      - "80:8000"
  redis:
    image: redis
