version: '2'
services:
  web:
    environment:
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/chatbot_website:/root/QueerAI/chatbot_website
    depends_on:
      - redis
  redis:
    image: redis
