version: '2'
services:
  test:
    command: "./main.py --test interactive"
    image: queerai:latest
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ${PWD}/data:/root/QueerAI/data
      - ${PWD}/save:/root/QueerAI/save
