#!/usr/bin/env bash

docker build \
  --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  --build-arg AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
  -f $DOCKERFILE_PATH -t $IMAGE_NAME .

